service: token-sale-whitelist

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  stage: stag008
  region: us-east-1
  runtime: nodejs6.10
  memorySize: 256
  timeout: 5
  versionFunctions: true
  environment:  ${self:custom.externalConfig.environment}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:PutRecords
      Resource: "arn:aws:kinesis:${self:provider.region}:*:stream/${self:custom.stage}-${self:service}-*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.stage}-${self:service}-*"

custom:
  stage: ${opt:stage, self:provider.stage}
  externalConfig: ${file(env.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
  cors: ${self:custom.externalConfig.cors}
  dynamodbThroughput: ${self:custom.externalConfig.dynamodbThroughput}
  vpc: ${self:custom.externalConfig.vpc}
  kinesis: ${self:custom.externalConfig.kinesis}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:provider.environment.CB_ENV_NAME}-events
            sources: [./data/events.json]
  serverless-offline:
    port: 9000

functions:

  graphql-api:
    name: ${self:provider.environment.CB_ENV_NAME}-graphql-api
    handler: lambda/graphql-api.post
    events:
    - http:
        path: /v1.0/graphql
        method: post
        cors: true

  ### Backoffice functions
  backoffice-kinesis-processor:
    name: ${self:provider.environment.CB_ENV_NAME}-backoffice-kinesis-processor
    handler: lambda/backoffice-kinesis-processor.process
    timeout: 30
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - EventsDynamoDbTable
              - StreamArn

  backoffice-coinfirm-processor:
    name: ${self:provider.environment.CB_ENV_NAME}-backoffice-coinfirm-processor
    handler: lambda/backoffice-coinfirm-processor.process
    timeout: 30
    events:
      - stream:
          type: kinesis
          batchSize: 100
          startingPosition: TRIM_HORIZON
          arn:
            Fn::GetAtt:
              - KinesisStream
              - Arn

resources:
  Resources:
    WebsiteS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cb-${self:provider.environment.CB_ENV_NAME}-website
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    WebsiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebsiteS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: WebsiteS3Bucket
                  - "/*"
    EventsDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.CB_ENV_NAME}-events
        AttributeDefinitions:
          -
            AttributeName: address
            AttributeType: S
          -
            AttributeName: event_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: address
            KeyType: HASH
          -
            AttributeName: event_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.dynamodbThroughput.events.read}
          WriteCapacityUnits: ${self:custom.dynamodbThroughput.events.write}
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    KinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:provider.environment.CB_ENV_NAME}-events
        ShardCount: ${self:custom.kinesis.shardCount}
        RetentionPeriodHours:  ${self:custom.kinesis.retentionPeriodHours}
